# Generated by Django 5.0.2 on 2024-02-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('is_published', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='Publication Status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
