# Generated by Django 5.0.2 on 2024-03-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_status_delete_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_published',
        ),
    ]
