# Generated by Django 5.0.2 on 2024-03-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0004_alter_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='labels.labels', verbose_name='Label'),
        ),
    ]
