# Generated by Django 5.0.2 on 2024-03-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0005_tasks_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='label',
        ),
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.ManyToManyField(blank=True, to='labels.labels', verbose_name='Label'),
        ),
    ]
