# Generated by Django 5.0.2 on 2024-03-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0006_remove_tasks_label_tasks_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='task_labels', to='labels.labels', verbose_name='Label'),
        ),
    ]
