# Generated by Django 5.0.3 on 2024-03-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='created_by_user_id',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='performer_user_id',
            new_name='executor_id',
        ),
    ]
