# Generated by Django 5.0.3 on 2024-03-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='executor_id',
            new_name='executor',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
    ]
