# Generated by Django 5.0.3 on 2024-03-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_author_id_tasks_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='label',
            new_name='labels',
        ),
    ]
